name: Open Energy Dashboard (OED)
markdown: kramdown

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

# liquid:
#   error_mode: strict
#   strict_variables: true
#   strict_filters: true

defaults:
  -
    scope:
      path: ""
    values:
      navbarShown: true
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "developer"
    values:
      layout: developer
  -
    scope:
      path: "help"
    values:
      layout: help