name: Open Energy Dashboard (OED)
markdown: kramdown

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      navbarShown: true
  -
    scope:
      path: "developer"
    values:
      layout: developer
  -
    scope:
      path: "help"
    values:
      layout: help